#!/bin/bash

# Custom build for Docker Hub
# see: https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1

[[ -e hooks/environment ]] && . hooks/environment

docker run \
  --rm \
  --name ${DOCKER_NAME_SPACE}-forgejo-runner \
  --hostname ${DOCKER_NAME_SPACE}-forgejo-runner \
  --interactive \
  --tty \
  --cap-add=SYS_ADMIN \
  --entrypoint '' \
  ${PORTS} \
  ${VOLUMES} \
  ${ENV} \
  ${DOCKER_NAME_SPACE}/forgejo-runner:${CONTAINER_VERSION} \
  /bin/bash
